const semanticColorKeys = [
  "accent.blue.bg",
  "accent.blue.border",
  "accent.blue.fg",
  "accent.blue.onSolid",
  "accent.blue.solid",
  "accent.cyan.bg",
  "accent.cyan.border",
  "accent.cyan.fg",
  "accent.cyan.onSolid",
  "accent.cyan.solid",
  "accent.purple.bg",
  "accent.purple.border",
  "accent.purple.fg",
  "accent.purple.onSolid",
  "accent.purple.solid",
  "border.default",
  "border.disabled",
  "border.focus",
  "border.strong",
  "border.subtle",
  "brand.bg",
  "brand.border",
  "brand.fg",
  "brand.onSolid",
  "brand.solid",
  "brand.active",
  "brand.disabled",
  "brand.launch",
  "chart.diverging.negative",
  "chart.diverging.neutral",
  "chart.diverging.positive",
  "chart.sequential.high",
  "chart.sequential.low",
  "chart.sequential.mid",
  "market.down.bg",
  "market.down.border",
  "market.down.fg",
  "market.down.onSolid",
  "market.down.solid",
  "market.flat.bg",
  "market.flat.border",
  "market.flat.fg",
  "market.flat.onSolid",
  "market.flat.solid",
  "market.up.bg",
  "market.up.border",
  "market.up.fg",
  "market.up.onSolid",
  "market.up.solid",
  "overlay.backdrop",
  "overlay.black.muted",
  "overlay.black.scrim",
  "overlay.black.strong",
  "overlay.black.subtle",
  "overlay.brand.muted",
  "overlay.brand.scrim",
  "overlay.brand.strong",
  "overlay.brand.subtle",
  "overlay.danger.muted",
  "overlay.danger.scrim",
  "overlay.danger.strong",
  "overlay.danger.subtle",
  "overlay.down.muted",
  "overlay.down.scrim",
  "overlay.down.strong",
  "overlay.down.subtle",
  "overlay.info.muted",
  "overlay.info.scrim",
  "overlay.info.strong",
  "overlay.info.subtle",
  "overlay.inverse.muted",
  "overlay.inverse.scrim",
  "overlay.inverse.strong",
  "overlay.inverse.subtle",
  "overlay.scrim",
  "overlay.up.muted",
  "overlay.up.scrim",
  "overlay.up.strong",
  "overlay.up.subtle",
  "overlay.warning.muted",
  "overlay.warning.scrim",
  "overlay.warning.strong",
  "overlay.warning.subtle",
  "overlay.white.muted",
  "overlay.white.scrim",
  "overlay.white.strong",
  "overlay.white.subtle",
  "status.danger.bg",
  "status.danger.border",
  "status.danger.fg",
  "status.danger.onSolid",
  "status.danger.solid",
  "status.info.bg",
  "status.info.border",
  "status.info.fg",
  "status.info.onSolid",
  "status.info.solid",
  "status.neutral.bg",
  "status.neutral.border",
  "status.neutral.fg",
  "status.neutral.onSolid",
  "status.neutral.solid",
  "status.success.bg",
  "status.success.border",
  "status.success.fg",
  "status.success.onSolid",
  "status.success.solid",
  "status.warning.bg",
  "status.warning.border",
  "status.warning.fg",
  "status.warning.onSolid",
  "status.warning.solid",
  "surface.canvas",
  "surface.disabled",
  "surface.inverse",
  "surface.panel",
  "surface.raised",
  "surface.subtle",
  "text.disabled",
  "text.inverse",
  "text.link",
  "text.primary",
  "text.secondary",
  "text.tertiary"
];

const semanticSpacing = {
  "bottom-action-area-padding-x": "var(--layout-bottom-action-area-padding-x)",
  "card-padding-x": "var(--layout-card-padding-x)",
  "content-card-padding-x": "var(--layout-content-card-padding-x)",
  "content-plain-padding-x": "var(--layout-content-plain-padding-x)",
  "form-field-text-inset": "var(--layout-form-field-text-inset)",
  "list-row-padding-x": "var(--layout-list-row-padding-x)",
  "top-bar-padding-x": "var(--layout-top-bar-padding-x)",
};

const semanticRadius = {
  card: "var(--radius-card)",
  sheet: "var(--radius-sheet)",
  full: "var(--radius-full)",
};

module.exports = {
  theme: {
    extend: {
      colors: Object.fromEntries(
        semanticColorKeys.map((key) => [key.replace(/\./g, '-'), `var(--color-${key.replace(/\./g, '-')})`]),
      ),
      borderRadius: semanticRadius,
      spacing: semanticSpacing,
    },
  },
};
